=begin
#Noths

#www.notonthehighstreet.com API client

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Noths::RefundsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RefundsApi' do
  before do
    # run before each test
    @instance = Noths::RefundsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RefundsApi' do
    it 'should create an instance of RefundsApi' do
      expect(@instance).to be_instance_of(Noths::RefundsApi)
    end
  end

  # unit tests for api_v1_refunds_create
  # Refund an order
  # Refunds all or part of an order
  # @param token Authentication credential
  # @param order_id Order id
  # @param refund_reason Customer will see this message
  # @param cents 
  # @param [Hash] opts the optional parameters
  # @return [RefundResponse]
  describe 'api_v1_refunds_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
