# frozen_string_literal: true

# Unit tests for Noths::RefundsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RefundsApi' do
  let(:instance) { Noths::RefundsApi.new }

  describe 'test an instance of RefundsApi' do
    it 'should create an instance of RefundsApi' do
      expect(instance).to be_instance_of(Noths::RefundsApi)
    end
  end

  # unit tests for refunds_create
  # Refund an order
  # Refunds all or part of an order
  # @param order_id Order id
  # @param refund_reason Customer will see this message
  # @param cents 
  # @param [Hash] opts the optional parameters
  # @return [RefundResponse]
  describe 'refunds_create test' do
    it 'should work'
  end

end
