=begin
#Noths

#www.notonthehighstreet.com API client

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Noths::EnquiryMessage
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EnquiryMessage' do
  before do
    # run before each test
    @instance = Noths::EnquiryMessage.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EnquiryMessage' do
    it 'should create an instance of EnquiryMessage' do
      expect(@instance).to be_instance_of(Noths::EnquiryMessage)
    end
  end
  describe 'test attribute "body"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

